[sdl]
fullscreen=false
output=surface
autolock=false

[dosbox]
machine=pc9821
memsize=8
fastbioslogo=true
startbanner=false

[cpu]
core=normal
cputype=386
cycles=12000

[mixer]
nosound=true

[midi]
mididevice=none

[speaker]
pcspeaker=false
